"""
build.py — Clipalyst build script.

Packages src/main.py into a standalone Windows application using PyInstaller.

At build time, Gumroad credentials are read from .env and written to a
generated file (src/licence_config.py) which is bundled into the executable.
This file is listed in .gitignore and never committed to version control.

Usage
-----
    python build.py

Output
------
  dist/Clipalyst/    — PyInstaller output directory
  release/Clipalyst/ — Final distributable folder
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ROOT      = Path(__file__).resolve().parent
ENTRY     = ROOT / "src" / "main.py"
ICON      = ROOT / "assets" / "icon.ico"
APP_NAME  = "Clipalyst"
DIST_DIR  = ROOT / "dist" / APP_NAME
RELEASE   = ROOT / "release" / APP_NAME

# Generated at build time — never committed to version control
LICENCE_CONFIG = ROOT / "src" / "licence_config.py"

HIDDEN_IMPORTS = [
    "pystray",
    "pystray._win32",         # platform backend
    "customtkinter",
    "win32con",
    "win32clipboard",
    "win32gui",
    "win32process",
    "keyboard",
    "anthropic",
    "anthropic._client",
    "anthropic.types",
    "src.licence_config",
]

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------

def _check_prerequisites() -> None:
    if not ENTRY.exists():
        sys.exit(f"[ERROR] Entry point not found: {ENTRY}")
    if not ICON.exists():
        sys.exit(f"[ERROR] Icon file not found: {ICON}")

    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        sys.exit(
            "[ERROR] PyInstaller is not installed.\n"
            "Run:  pip install pyinstaller  (or activate your venv first)"
        )

    try:
        from dotenv import load_dotenv  # noqa: F401
    except ImportError:
        sys.exit(
            "[ERROR] python-dotenv is not installed.\n"
            "Run:  pip install python-dotenv  (or activate your venv first)"
        )

# ---------------------------------------------------------------------------
# Inject Gumroad credentials from .env into src/licence_config.py
# ---------------------------------------------------------------------------

def _generate_licence_config() -> None:
    from dotenv import load_dotenv

    env_path = ROOT / ".env"
    if not env_path.exists():
        sys.exit(
            "[ERROR] .env file not found.\n"
            "Create one in the project root with:\n"
            "  GUMROAD_PRODUCT_ID=your_product_id\n"
            "  GUMROAD_ACCESS_TOKEN=your_access_token"
        )

    load_dotenv(env_path)

    product_id    = os.getenv("GUMROAD_PRODUCT_ID", "").strip()
    access_token  = os.getenv("GUMROAD_ACCESS_TOKEN", "").strip()

    if not product_id:
        sys.exit("[ERROR] GUMROAD_PRODUCT_ID is missing or empty in .env")
    if not access_token:
        sys.exit("[ERROR] GUMROAD_ACCESS_TOKEN is missing or empty in .env")

    config_content = (
        "# AUTO-GENERATED by build.py — DO NOT EDIT OR COMMIT\n"
        "# This file is created at build time from .env and bundled\n"
        "# into the executable by PyInstaller. It is listed in .gitignore.\n"
        f'GUMROAD_PRODUCT_ID = "{product_id}"\n'
        f'GUMROAD_ACCESS_TOKEN = "{access_token}"\n'
    )

    LICENCE_CONFIG.write_text(config_content, encoding="utf-8")
    print(f"[build] Generated {LICENCE_CONFIG.relative_to(ROOT)}")

    # Ensure it is in .gitignore
    _ensure_gitignore("src/licence_config.py")


def _ensure_gitignore(*entries: str) -> None:
    gitignore = ROOT / ".gitignore"
    existing  = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    added     = []
    for entry in entries:
        if entry not in existing:
            existing += f"\n{entry}"
            added.append(entry)
    if added:
        gitignore.write_text(existing, encoding="utf-8")
        print(f"[build] Added to .gitignore: {', '.join(added)}")


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def _run_pyinstaller() -> None:
    hidden = []
    for imp in HIDDEN_IMPORTS:
        hidden.extend(["--hidden-import", imp])

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",           # overwrite previous build without asking
        "--clean",               # remove PyInstaller cache before building
        "--onedir",              # directory output (faster startup than --onefile)
        "--windowed",            # no console window
        f"--name={APP_NAME}",
        f"--icon={ICON}",
        # Bundle assets/ so icon.ico is available under sys._MEIPASS/assets/
        f"--add-data={ICON}{os.pathsep}assets",
        *hidden,
        str(ENTRY),
    ]

    print(f"\n[build] Running PyInstaller for '{APP_NAME}'…")
    print(f"[build] Command: {' '.join(cmd)}\n")

    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode != 0:
        sys.exit(f"[ERROR] PyInstaller exited with code {result.returncode}")

# ---------------------------------------------------------------------------
# Cleanup generated files
# ---------------------------------------------------------------------------

def _cleanup_licence_config() -> None:
    if LICENCE_CONFIG.exists():
        LICENCE_CONFIG.unlink()
        print(f"[build] Cleaned up {LICENCE_CONFIG.relative_to(ROOT)}")

# ---------------------------------------------------------------------------
# Copy to release/
# ---------------------------------------------------------------------------

def _copy_to_release() -> None:
    if not DIST_DIR.exists():
        sys.exit(f"[ERROR] Expected dist output not found: {DIST_DIR}")

    if RELEASE.exists():
        print(f"[build] Removing existing release directory: {RELEASE}")
        shutil.rmtree(RELEASE)

    print(f"[build] Copying {DIST_DIR} -> {RELEASE}")
    shutil.copytree(DIST_DIR, RELEASE)
    print(f"[build] Release ready at: {RELEASE}")

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    print("[build] Clipalyst build script starting…")
    print(f"[build] Root:  {ROOT}")
    print(f"[build] Entry: {ENTRY}")
    print(f"[build] Icon:  {ICON}")

    _check_prerequisites()
    _generate_licence_config()

    try:
        _run_pyinstaller()
    finally:
        # Always clean up the generated config, even if PyInstaller fails,
        # so credentials are never left sitting in the source tree.
        _cleanup_licence_config()

    _copy_to_release()

    print(f"\n[build] Build complete.  Distributable: {RELEASE}")


if __name__ == "__main__":
    main()