"""
licence.py — Activation-key validation for Clipalyst.

Key format
----------
Keys are 36-character strings (UUID-like) generated as:
  BASE = <email>:<timestamp_day>
  HMAC-SHA256(BASE, SECRET_SALT) → hex → first 32 chars
  Final key = XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX  (4-char groups separated by hyphens)

Validation: strip hyphens/spaces, HMAC the stored email + today's
date (rounded to the nearest N-day window), compare constant-time.
Because we ship a server-less desktop app the key covers a rolling
90-day activation window so keys don't expire after a single day.
"""

import hashlib
import hmac
import logging
import os
import re
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────
FREE_LIMIT     = 50     # max clipboard history items for free users
FREE_PIN_LIMIT = 3      # max pinned items for free users

# This salt is baked into the distributed binary.
# It is NOT a secret that prevents reverse-engineering — it just ensures keys
# generated by the server are structurally different from random strings.
_SALT = b"clipalyst-pro-2026"

# Activation window: key is valid for ±WINDOW_DAYS from the issuance epoch
_WINDOW_DAYS = 180


# ── Internal helpers ──────────────────────────────────────────────────────────

def _normalise(key: str) -> str:
    """Strip separators and convert to lowercase hex."""
    return re.sub(r"[\-\s]", "", key).lower()


def _epoch_bucket(ts: datetime) -> int:
    """Return the day-bucket (days since Unix epoch) for a given timestamp."""
    return int(ts.replace(tzinfo=timezone.utc).timestamp()) // 86400


def _expected_token(email: str, day_bucket: int) -> str:
    """Produce the 32-char hex token for an email + day bucket."""
    payload = f"{email.strip().lower()}:{day_bucket}".encode()
    return hmac.new(_SALT, payload, hashlib.sha256).hexdigest()[:32]


def _validate_key(key: str, email: str = "") -> bool:
    """
    Return True when *key* is a valid Pro activation key.

    The key encodes a day-bucket.  We try every bucket in the past
    WINDOW_DAYS days so that a key generated up to 6 months ago is
    still accepted.  This keeps things simple for users who don't
    re-enter their key often.

    If *email* is supplied, the key is also validated against that
    email.  Since we ship without a call-home server we accept keys
    that match *any* email too (anonymous keys), which the server can
    produce for edge cases.
    """
    token = _normalise(key)
    if len(token) != 32:
        return False

    today_bucket = _epoch_bucket(datetime.utcnow())

    candidates: list[str] = []
    for delta in range(_WINDOW_DAYS + 1):
        bucket = today_bucket - delta
        # Try with provided email (may be empty for anonymous keys)
        candidates.append(_expected_token(email, bucket))
        if email:
            # Also try the anonymous variant (empty email) issued by server
            candidates.append(_expected_token("", bucket))

    return any(hmac.compare_digest(token, c) for c in candidates)


# ── Public activation API ─────────────────────────────────────────────────────

# Module-level cache so callers don't hit disk on every is_pro() call.
_pro_active: bool | None = None
_settings_manager = None  # injected by tray.py / main.py at startup


def init(settings_manager) -> None:
    """Wire the licence module to the app's SettingsManager."""
    global _settings_manager, _pro_active
    _settings_manager = settings_manager
    stored_key   = settings_manager.get("activation_key", "")
    stored_email = settings_manager.get("activation_email", "")
    if stored_key:
        _pro_active = _validate_key(stored_key, stored_email)
        if not _pro_active:
            logger.warning(
                "Stored activation key is invalid or expired — reverting to Free tier."
            )
    else:
        _pro_active = False


def is_pro() -> bool:
    """Return True if a valid Pro licence is active."""
    return bool(_pro_active)


def activate(key: str, email: str = "") -> tuple[bool, str]:
    """
    Attempt to activate Pro with *key*.

    Returns
    -------
    (success: bool, message: str)
    """
    global _pro_active
    if _validate_key(key, email):
        _pro_active = True
        if _settings_manager:
            _settings_manager.set("activation_key",   key.strip())
            _settings_manager.set("activation_email", email.strip().lower())
        logger.info("Pro licence activated.")
        return True, "✅ Pro activated! Please restart the app to unlock all features."
    else:
        logger.warning("Invalid activation key entered.")
        return False, "❌ Invalid or expired activation key. Please check and try again."


def deactivate() -> None:
    """Remove the stored licence and revert to Free tier."""
    global _pro_active
    _pro_active = False
    if _settings_manager:
        _settings_manager.set("activation_key",   "")
        _settings_manager.set("activation_email", "")
    logger.info("Pro licence deactivated.")
